### ISSUE TITLE
Support for device disconnect detection

### ISSUE THREAD

**Issue by ZKXU** [bojidartonchev/device_manager#1]
Hi , does this package support the device disconnect detection? I would like to use this package to monitor the UART port plugin and unplug status. Thanks for your support!

**Comment by bojidartonchev** [comment]
Hello,

Maybe it could be implemented easily, but i don't know when I will have time for it. I will try to find time in the next week or two. Meanwhile, I rely on serial connection's error callbacks to detect device disconnect. So I only needed a callback when some device had been connected again to try restore the connection. Maybe that could help you.

If you are in hurry, you can try to implement it. P.R are always welcomed. :)

**Comment by ZKXU** [comment]
Hi,
Thanks for your feedback, I'm trying to implement the related feature based on your package these day and will update to you after I got some progress.

**Comment by bojidartonchev** [comment]
Hello,

I have added device disconnect detection in v0.0.2 of the plugin.

```
DeviceManager().addListener(() {
  var event = DeviceManager().lastEvent;
  if (event != null) {
    if (event.eventType == EventType.add) {
      ....
    } else if (event.eventType == EventType.remove) {
      ....
    }
  }
});

```

For more complex example, please refer to the [example](https://github.com/bojidartonchev/device_manager/tree/main/example).
